### ISSUE TITLE
[Bug Fix] Can't add any action on the items. (DeluxeMenus)

### ISSUE THREAD

**Issue by OPADILOP** [Xezard/DevMC#1]

**Comment by Xezard** [comment]
Yep, I checked that. I'll fix it in the next update, thanks!

**Comment by Xezard** [comment]
![image](https://user-images.githubusercontent.com/17483454/185811493-c007d845-d3d5-4efa-8bbd-aa32d21c71f6.png)
Fixed it. Thanks for the report!
