### ISSUE TITLE
[Bug Report] Same action issue again showed up.

### ISSUE THREAD

**Issue by OPADILOP** [Xezard/DevMC#6]
![Screenshot 2022-09-21 154919](https://user-images.githubusercontent.com/86042583/191473783-38384cb5-c5f2-47d2-8df0-346bc604e943.png)
![Screenshot 2022-09-21 154836](https://user-images.githubusercontent.com/86042583/191473791-31123292-491d-447a-8e0b-6cdd72ee930e.png)
I haven't forgot that you have already fixed the action issue. But this problem again showed up. Fix it soon.

**Comment by Xezard** [comment]
Yep, I see. I'll fix it as soon as possible.

**Comment by Xezard** [comment]
In order for deny_commands to be displayed in the requirements section, you need to create at least one requirement. Otherwise, the requirements section is not created - so the deny _commands section is not created either.
